connect to vault and retreive secrets

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,14 +1,51 @@
 version: 2.1
-
-workflows:
-  vault-workflow:
-    jobs: 
-      - vault-connection
-
+commands: 
+  install-vault:
+    steps:
+      - run:
+          name: Install Vault and prereqs
+          command: |
+            vault -h && exit 0 || echo "Installing vault"
+            # only runs if vault command above fails
+            cd /tmp
+            wget https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip
+            unzip vault_1.12.2_linux_amd64.zip
+            sudo mv vault /usr/local/bin        
+            vault -h
+  vault-auto-auth:
+    description: "Use Vault auto auth to load secrets"
+    steps:
+      - run:
+          name: Auto-authenticate with Vault
+          command: |
+            # Write the CircleCI provided value to a file read by Vault
+            echo $CIRCLE_OIDC_TOKEN > .circleci/vault/token.json
+            # Substitute the env vars in our context to render the Vault config file
+            sudo apt update && sudo apt install gettext-base
+            envsubst < .circleci/vault/agent.hcl.tpl > .circleci/vault/agent.hcl
+            # This config indicates which secrets to collect and how to authenticate     
+            vault agent -config=.circleci/vault/agent.hcl
+      - run:
+          name: Set Environment Variables from Vault
+          command: |
+            # In order to properly expose values in Environment, we _source_ the shell values written by agent
+            source .circleci/vault/setenv
 jobs:
-  vault-connection:
-    docker:
-      - image: cimg/node:17.2.0
+  setup-vault-and-load-secrets:
+    docker: 
+      - image: cimg/base:2023.01
     steps:
       - checkout
-      - run: echo "Hello World" 
+      - install-vault
+      - vault-auto-auth
+      - run: 
+          name: Use secrets retrieved from Vault in a subsequent step
+          command: |
+            echo "Username is $SECRET_DEMO_USERNAME, password is $SECRET_DEMO_PASSWORD"
+workflows:
+  vault: 
+    jobs:
+      - setup-vault-and-load-secrets:
+          context:
+            - circleci-vault-demo
+# VS Code Extension Version: 1.5.1
